[project]
name = "footfall-counter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "filterpy>=1.4.5",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "scipy>=1.16.3",
    "ultralytics>=8.3.223",
    "yt-dlp>=2025.10.22",
]
